version: 2

updates:
  # Maintain Docker dependencies.
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  # Maintain GitHub Actions dependencies.
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"

  # Maintain Python dependencies.
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      minor-dependencies:
        update-types:
          - "minor"
    versioning-strategy: increase
    allow:
      - dependency-type: "all"
