version: 2

updates:
  # Maintain Docker dependencies.
  - package-ecosystem: docker
    assignees:
      - 'h-holm'
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  # Maintain GitHub Actions dependencies.
  - package-ecosystem: github-actions
    assignees:
      - 'h-holm'
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - '*'

  # Maintain Python dependencies.
  - package-ecosystem: pip
    assignees:
      - 'h-holm'
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      minor-and-patch:
        update-types:
          - 'patch'
          - 'minor'
      major:
        update-types:
          - 'major'
    versioning-strategy: increase
    allow:
      - dependency-type: 'all'
