repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-docstring-first
      - id: debug-statements
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=auto"] # Replace "auto" with "lf" to enforce Linux/Mac line endings or "crlf" for Windows

  - repo: local
    hooks:
      - id: hatch-lint
        name: hatch-lint
        entry: hatch run lint:all
        language: system
        types_or: [python, pyi, jupyter]
        exclude: src/python_project/__version__.py

  # # Ruff replaces black, flake8, autoflake, isort and more
  # - repo: https://github.com/charliermarsh/ruff-pre-commit
  #   rev: "v0.6.7" # Keep consistent with the Hatch config in the `pyproject.toml` file.
  #   hooks:
  #     - id: ruff
  #     - id: ruff-format
  #       args: [--check, --config, ./pyproject.toml]

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v1.11.2" # Keep consistent with the Hatch config in the `pyproject.toml` file.
  #   hooks:
  #     - id: mypy
  #       args: ["--install-types", "--non-interactive"]
  #       additional_dependencies:
  #         - pydantic~=2.9.1
  #         - types-tabulate
  #         - types-cachetools
